version: "3"
services:

  node:
    image: node
    ports:
      - "1881"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017"
