---
  - name: python installation
    hosts: all
    become: true
    gather_facts: false
    tasks:
      - name: install python
        raw: apt -y update && apt install -y python-minimal

  - name: Nginx install with docker
    hosts: public
    become: true
    roles:
      - { role: nginx }


  - name: Node install with docker
    hosts: private
    become: true
    roles:
      - { role: node }







